# Generated by Django 4.1.4 on 2023-02-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0002_coupon_coupon_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='activ_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='exp_date',
            field=models.DateTimeField(null=True),
        ),
    ]
