# Generated by Django 4.1.4 on 2023-02-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0003_coupon_activ_date_alter_coupon_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
