# Generated by Django 4.1.4 on 2023-02-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminp', '0004_coupon_min_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon_product',
        ),
    ]
