# Generated by Django 4.1.4 on 2023-02-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variation_variation_category_multiimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiimages',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='multiimages',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='multiimages',
            name='image3',
        ),
    ]
