# Generated by Django 4.1.7 on 2023-02-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_image_remove_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
