# Generated by Django 4.1.7 on 2023-03-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
