# Generated by Django 4.1.4 on 2023-01-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
    ]
