# Generated by Django 4.1.4 on 2023-02-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variation_variation_category'),
        ('cart', '0007_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
