# Generated by Django 4.1.4 on 2023-02-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='variations',
        ),
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
