# Generated by Django 4.1.4 on 2023-02-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderproduct_variation_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='paymet',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='New', max_length=10),
        ),
    ]
