# Generated by Django 4.1.4 on 2023-02-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Out For Delivery', 'Out For Delivery'), ('Packed', 'Packed'), ('New', 'New')], default='New', max_length=20),
        ),
    ]
