# Generated by Django 4.1.4 on 2023-02-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('New', 'New')], default='New', max_length=20),
        ),
    ]
