# Generated by Django 4.1.4 on 2023-02-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Shipped', 'Shipped'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='New', max_length=20),
        ),
    ]
