# Generated by Django 4.1.4 on 2023-02-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('New', 'New'), ('Packed', 'Packed'), ('Shipped', 'Shipped')], default='New', max_length=20),
        ),
    ]
