# Generated by Django 4.1.4 on 2023-02-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Packed', 'Packed')], default='New', max_length=20),
        ),
    ]
