# Generated by Django 4.1.7 on 2023-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('New', 'New'), ('Shipped', 'Shipped')], default='New', max_length=20),
        ),
    ]
